version: '3'

services:
  flask-app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"

